# build configuration
- in: /input.html
  out: /output.html
  pipeline:
    - template:inline
    - banner:gostatic
- in: /input-without-pi.html
  out: /output-without-pi.html
  pipeline:
    - template:style.xsl
    - banner:gostatic
