# build configuration
- in: /input.xml
  out: /output1.html
  pipeline:
    - template:inline
    - banner:gostatic
- in: /input.html
  out: /output2.html
  pipeline:
    - template:style.xsl
    - banner:gostatic
